2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_setup.py:_flush():76] Configure stats pid to 77239
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_setup.py:_flush():76] Loading settings from /home/talae/.config/wandb/settings
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_setup.py:_flush():76] Loading settings from /home/talae/DRL_HW3/DRL_HW3/wandb/settings
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'scripts/Function_based/train_DQN.py', 'program': '/home/talae/DRL_HW3/DRL_HW3/scripts/Function_based/train_DQN.py'}
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_init.py:_log_setup():461] Logging user logs to /home/talae/DRL_HW3/DRL_HW3/wandb/run-20250417_230936-f6twou4f/logs/debug.log
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_init.py:_log_setup():462] Logging internal logs to /home/talae/DRL_HW3/DRL_HW3/wandb/run-20250417_230936-f6twou4f/logs/debug-internal.log
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_init.py:init():495] calling init triggers
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_init.py:init():498] wandb.init called with sweep_config: {}
config: {}
2025-04-17 23:09:36,192 INFO    MainThread:77239 [wandb_init.py:init():548] starting backend
2025-04-17 23:09:36,192 INFO    MainThread:77239 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-17 23:09:36,193 INFO    MainThread:77239 [backend.py:ensure_launched():217] starting backend process...
2025-04-17 23:09:36,194 INFO    MainThread:77239 [backend.py:ensure_launched():222] started backend process with pid: 78872
2025-04-17 23:09:36,194 INFO    MainThread:77239 [wandb_init.py:init():558] backend started and connected
2025-04-17 23:09:36,195 INFO    MainThread:77239 [wandb_init.py:init():634] updated telemetry
2025-04-17 23:09:36,198 INFO    MainThread:77239 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2025-04-17 23:10:06,198 INFO    MainThread:77239 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2025-04-17 23:10:06,198 ERROR   MainThread:77239 [wandb_init.py:init():674] backend process timed out
2025-04-17 23:10:06,198 ERROR   MainThread:77239 [wandb_init.py:init():685] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2025-04-17 23:10:06,203 ERROR   MainThread:77239 [wandb_init.py:init():1070] error
Traceback (most recent call last):
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 689, in init
    backend.cleanup()
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/talae/miniconda3/envs/env_isaaclab/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
